name: CloudFormation build and deploy pipeline
on: push

jobs:
  lint:
    name: CFT Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@1.6.0
