name: CloudFormation build and deploy pipeline
on: 
  push:
    branches:
    - master
    paths:
    - 'iac/**' 
    - '.github/workflows/**'   

jobs:

  cloudformation-linter:
    name: CFT Lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Inspect context
        run: |
          echo This workflow on ${{ github.repository }} was started by ${{ github.actor }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: cfn-lint
        uses: ScottBrenner/cfn-lint-action@1.6.0
        with:
          args: "**/iac/*"
  
  deploy:
    name: CFT Upload to Repo and Deploy to Test Stack
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Integrate with Takeda secrets mgmt    

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to Target Bucket
        run: |
          aws s3 sync iac s3://qf-s3-github-actions-deploy-bucket
        # modify to target JFrog Artifactory

      # # Untested JFrog code
      # - name: Setup JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v1
      #   env:
      #     JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
      # - name: Run JFrog CLI
      #   run: |
      #     jfrog --version
      #     # Collect environment variables for the build
      #     jfrog rt bce
      #     # Collect VCS details from git and add them to the build
      #     jfrog rt bag
      #     # Publish build info
      #     jfrog rt bp 

      # TODO: add taskcat test runs against additional regions
      #  https://github.com/aws-quickstart/taskcat

      - name: Deploy Test Stack
        uses: mgenteluci/cloudformation-deploy-action@v1.4.0
        env:
          TEMPLATE: 'iac/sqs-example.yaml'
          AWS_STACK_NAME: 'my-stack'
          AWS_REGION: 'us-east-1'
          AWS_DEPLOY_BUCKET: ${{secrets.PROD_AWS_DEPLOY_BUCKET}}

        # Parameterize the TEMPLATE that is run by Cloudformation
        # Parameterize the bucket prefix also

      - name: Describe Test Stack
        run: |
          aws cloudformation describe-stacks --stack-name 'my-stack'
      
      - name: Delete Test Stack
        run: |
          aws cloudformation delete-stack --stack-name 'my-stack'