name: CloudFormation build and deploy pipeline
on: push

jobs:
  cloudformation-linter:
    
    name: CFT Lint
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cfn-lint
        uses: ScottBrenner/cfn-lint-action@1.6.0
        with:
          args: "**/iac/*.json"
        with:
          args: "**/iac/*.yaml"
        with:
          args: "**/iac/*.yml"
