name: CloudFormation build and deploy pipeline
on: push

jobs:

  # cloudformation-linter:
  #   name: CFT Lint
  #   runs-on: ubuntu-latest
  
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: cfn-lint
  #       uses: ScottBrenner/cfn-lint-action@1.6.0
  #       with:
  #         args: "**/iac/*"
  
  deploy:
    name: CFT Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{secrets.PROD_AWS_DEPLOY_BUCKET}}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: mgenteluci/cloudformation-deploy-action@v1.4.0
        env:
          TEMPLATE: 'iac/sqs-example.yml'
          AWS_STACK_NAME: 'my-stack'
          AWS_REGION: 'us-east-1'
          # AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          # AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          # AWS_DEPLOY_BUCKET: ${{secrets.PROD_AWS_DEPLOY_BUCKET}}
          AWS_BUCKET_PREFIX: stacks/ec2

      # - name: Copy files to target bucket with the AWS CLI
      #   run: |
      #     aws s3 sync . s3://qf-s3-github-actions-deploy-bucket