name: CloudFormation build and deploy pipeline
on: push

jobs:

  cloudformation-linter:
    name: CFT Lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cfn-lint
        uses: ScottBrenner/cfn-lint-action@1.6.0
        with:
          args: "**/iac/*"
  
  deploy:
    name: CFT Upload and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Integrate with Takeda secrets mgmt    

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to target bucket
        run: |
          aws s3 sync iac s3://stacks/ec2/qf-s3-github-actions-deploy-bucket
        # modify to target JFrog Artifactory

      - name: Deploy
        uses: mgenteluci/cloudformation-deploy-action@v1.4.0
        env:
          TEMPLATE: 'iac/sqs-example.yaml'
          AWS_STACK_NAME: 'my-stack'
          AWS_REGION: 'us-east-1'
          AWS_DEPLOY_BUCKET: ${{secrets.PROD_AWS_DEPLOY_BUCKET}}

        # Parameterize the TEMPLATE that is run by Cloudformation
        # Parameterize the bucket prefix also

