name: pre-commit

on: 
  push:
    branches:
    - master
    # paths:
    # - 'iac/**'
    # - '.github/**'

jobs:
   pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0